name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # to be able to publish a GitHub release
  id-token: write # Required for OIDC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --no-git-checks

      - name: Generate a changelog
        run: pnpm exec smarty-release changelog -vv -o --latest
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Github Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: CHANGELOG.md
          prerelease: ${{ contains(github.ref_name, '-') }}
